version: '3.7'

services:
    lee8:
        build:
            context: .
        image: nderwin/lee8:latest
        container_name: lee8
        depends_on:
          - database
        ports:
          - "8080:8080"
          - "9990:9990"
    database:
        image: postgres:9.6.3
        container_name: lee8db
        command: postgres -c log_statement=all
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_username
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB: lee8db
        volumes:
          - ./database:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        secrets:
          - postgres_username
          - postgres_password

secrets:
    postgres_username:
        file: ./dockersecrets/postgres_username
    postgres_password:
        file: ./dockersecrets/postgres_password
